language: 
  - python
python:
  - "3.6.7"

services:
  - postgresql
  
env: 
  -DJANGO=2.2.1 

install:

  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE clintondb;" -U postgres    

script:
  - python manage.py migrate
  - python manage.py test blog

# deploy:
#   provider: heroku
#   api_key:
#     secure: "385b3e25-f8d4-4f8a-b232-f73776b4884d"
