language: python
python:
  - "3.6.7"
install:
  - pip install -r requirements.txt
  - cd ..
  - django-admin.py startproject --template=./edge --extension=py,md,html,env django_project
  - cp django_project/settings /local.sample.env django_project/settings/local.env
  - python manage.py migrate
script:
  - python manage.py test blog