language: python
python:
    - "3.6"
    

services:
    - postgresql
  
env: 
    -DJANGO=2.2.1 

before_install:
  - export DJANGO_SETTINGS_MODULE = django_project.settings

install:
      - pip install -r requirements.txt
      - pip install psycopg2 --quiet

before_script:
- psql -c "CREATE DATABASE clintondb;" -U postgres    

      script:
        - python manage.py syncdb --noinput
        - python manage.py test