language: python

sudo: false

python:
  - "3.6"

services:
  - postgresql


# Match postgresql version to that in conf/pillar/project.sls
# addons:
postgresql: "11"

# cache:
#   directories:
#     - $HOME/.cache/pip
#     - $HOME/.npm
#     - $HOME/.nvm
#     - $HOME/.cache/node_modules
#     - $HOME/.cache/venvs

# env:
#   - DJANGO_SETTINGS_MODULE="{{ project_name }}.settings.dev"

install:
  - pip install -U pip
  - pip install -U -r requirements.txt
  

before_script:
  psql -c 'create database travis_ci_test;' -U postgres
  # - createdb --encoding=UTF-8 {{ django_project }} --username=postgres --owner=`whoami`
  # Uncomment for Requires.IO pushes of develop and master merges (not pull-request builds)
  # Requires the $REQUIRES_IO_TOKEN environment variable defined at Travis CI for this project
  # See developer documentation section on depdency tracking for more information.
  # - if [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then requires.io update-branch -t $REQUIRES_IO_TOKEN -r rescueid -n $(echo $TRAVIS_BRANCH | sed "s|/|__|g") . ; fi
  # Uncomment for PostGIS support
  # - psql service_info -c "CREATE EXTENSION postgis;" -U postgres

script:
  - python manage.py migrate
  # --dry-run | grep 'No changes detected' || (echo 'There are changes which require migrations.' && exit 1)
  - python manage.py test blog 
  # - coverage report -m --fail-under 80