language: 
  - python
python:
  - "3.6.7"

services:
  - postgresql
  
env: 
  -DJANGO=2.2.1 

install:

  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE gecko;" -U postgres    

script:
  - python manage.py migrate
  - python manage.py test blog

deploy:
  provider: heroku
  api_key:
    secure: "265eba55-6a34-4345-baac-fe8b96d79a21"
